- Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

In [19]:
import pandas as pd
from scipy import stats as stats
import numpy as np


In [20]:
data= pd.read_csv('BuyerRatio.csv')

In [21]:
data.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [22]:
data1=data.iloc[:,1:5]
data1

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [23]:
data1.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [24]:
val=stats.chi2_contingency(data1)
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [25]:
type(val)

tuple

In [26]:
no_of_rows=len(data1.iloc[0:2,0])
no_of_columns=len(data1.iloc[0,0:4])
degree_of_f=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=',degree_of_f)

Degree of Freedom= 3


In [27]:
Expected_value=val[3]
Expected_value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [28]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(data1.values,Expected_value)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic

1.5152956451130446

In [29]:
critical_value=chi2.ppf(0.95,3)
critical_value


7.814727903251179

In [30]:
if chi_square_statestic >= critical_value:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')


Independent (fail to reject H0)


In [31]:
pvalue=1-chi2.cdf(chi_square_statestic,3)
pvalue


0.6787446296467897

In [32]:
if pvalue <= 0.05:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')


Independent (fail to reject H0)
